In [2]:
#Esta no pude hacerla con web scrapping, así que descargué los datos en un excel.

import pandas as pd

ruta_excel = r'C:\Users\orlan\Documents\EDA\Vizquel\Estadisticas defensa.xlsx'
df_vizquel_defensa = pd.read_excel(ruta_excel)
print(df_vizquel_defensa)

    Year  Age   Tm Pos  Lg    G   GS     CG     Inn     Ch  ...  Rtot  Rdrs  \
0   1989   22  SEA  SS  AL  143  131   95.0  1124.0  614.0  ...   6.0   NaN
1   1990   23  SEA  SS  AL   81   78   67.0   680.0  349.0  ...  13.0   NaN
2   1991   24  SEA  SS  AL  138  123  114.0  1134.1  659.0  ...  14.0   NaN
3   1991   24  SEA  2B  AL    1    0    0.0     1.0    0.0  ...   NaN   NaN
4   1992   25  SEA  SS  AL  136  128  120.0  1152.0  633.0  ...  13.0   NaN
5   1993   26  SEA  SS  AL  155  150  140.0  1330.2  735.0  ...  16.0   NaN
6   1993   26  SEA  DH  AL    2    0    NaN     NaN    NaN  ...   NaN   NaN
7   1994   27  CLE  SS  AL   69   68   66.0   612.2  323.0  ...   4.0   NaN
8   1995   28  CLE  SS  AL  136  135  125.0  1187.0  624.0  ...   1.0   NaN
9   1996   29  CLE  SS  AL  150  149  135.0  1312.1  693.0  ...   1.0   NaN
10  1997   30  CLE  SS  AL  152  149  141.0  1307.1  684.0  ...   2.0   NaN
11  1998   31  CLE  SS  AL  151  149  134.0  1316.0  720.0  ...   9.0   NaN
12  1999   32  CLE  SS  AL  143  140  121.0  1214.1  632.0  ...  14.0   NaN
13  1999   32  CLE  OF  AL    1    0    0.0     1.0    0.0  ...   0.0   NaN
14  1999   32  CLE  RF  AL    1    0    0.0     1.0    0.0  ...   0.0   NaN
15  2000   33  CLE  SS  AL  156  154  140.0  1328.2  648.0  ...  -1.0   NaN
16  2001   34  CLE  SS  AL  154  152  140.0  1320.2  640.0  ...  -8.0   NaN
17  2002   35  CLE  SS  AL  150  148  141.0  1291.0  677.0  ...  -2.0   NaN
18  2003   36  CLE  SS  AL   64   63   59.0   551.1  324.0  ...  15.0  10.0
19  2004   37  CLE  SS  AL  147  141  126.0  1245.0  607.0  ...  -1.0   2.0
20  2005   38  SFG  SS  NL  150  144  141.0  1292.1  668.0  ...   7.0   1.0
21  2006   39  SFG  SS  NL  152  148  131.0  1281.1  599.0  ...   2.0   7.0
22  2007   40  SFG  SS  NL  143  136  130.0  1219.1  651.0  ...  20.0  16.0
23  2008   41  SFG  SS  NL   84   76   61.0   657.2  289.0  ...   3.0   9.0
24  2009   42  TEX  SS  AL   27   22   17.0   196.2  108.0  ...   6.0   2.0
25  2009   42  TEX  3B  AL   20    9    8.0   101.0   27.0  ...   4.0   5.0
26  2009   42  TEX  2B  AL   16   14   13.0   126.0   72.0  ...   2.0   0.0
27  2010   43  CHW  3B  AL   83   62   55.0   582.1  144.0  ...  -4.0  -7.0
28  2010   43  CHW  2B  AL   19   18   12.0   151.0   63.0  ...  -2.0   0.0
29  2010   43  CHW  SS  AL    9    8    4.0    61.0   28.0  ...   0.0   1.0
30  2010   43  CHW  DH  AL    1    1    NaN     NaN    NaN  ...   NaN   NaN
31  2011   44  CHW  3B  AL   29   20   17.0   182.0   44.0  ...   0.0   1.0
32  2011   44  CHW  2B  AL   16   14   10.0   130.1   61.0  ...  -5.0  -1.0
33  2011   44  CHW  SS  AL    9    8    7.0    72.0   26.0  ...   0.0  -1.0
34  2011   44  CHW  DH  AL    3    0    NaN     NaN    NaN  ...   NaN   NaN
35  2011   44  CHW  1B  AL    1    0    0.0     3.0    2.0  ...   0.0   0.0
36  2012   45  TOR  2B  AL   24   18   16.0   164.0   84.0  ...  -1.0   2.0
37  2012   45  TOR  3B  AL   18   10    9.0   111.2   44.0  ...   3.0   1.0
38  2012   45  TOR  SS  AL   10    9    6.0    73.0   30.0  ...   0.0   1.0
39  2012   45  TOR  1B  AL    2    0    0.0     5.0    6.0  ...   0.0   0.0
40  2012   45  TOR  DH  AL    1    0    NaN     NaN    NaN  ...   NaN   NaN
41  2012   45  TOR  LF  AL    1    0    0.0     0.2    0.0  ...   0.0   0.0
42  2012   45  TOR  OF  AL    1    0    0.0     0.2    0.0  ...   0.0   0.0

    Rtot/yr  Rdrs/yr   RF/9  RF/G  lgFld%  lgRF9  lgRFG        Awards
0       7.0      NaN   4.77  4.17   0.971   4.79   4.74           NaN
1      22.0      NaN   4.53  4.22   0.973   4.74   4.69           NaN
2      14.0      NaN   5.13  4.68   0.971   4.67   4.66           NaN
3       NaN      NaN   0.00  0.00     NaN   5.40   5.20           NaN
4      13.0      NaN   4.89  4.60   0.969   4.71   4.69           NaN
5      14.0      NaN   4.87  4.65   0.973   4.69   4.64            GG
6       NaN      NaN    NaN   NaN     NaN    NaN    NaN            GG
7       8.0      NaN   4.66  4.59   0.969   4.64   4.60            GG
8       1.0      NaN   4.66  4.52   0.974   4.71   4.65            GG
9       1.0      NaN   4.62  4.49   0.971   4.66   4.64            GG
10      1.0      NaN   4.64  4.43   0.974   4.55   4.51            GG
11      8.0      NaN   4.89  4.74   0.972   4.71   4.66         AS,GG
12     14.0      NaN   4.57  4.31   0.970   4.73   4.66  AS,MVP-16,GG
13      0.0      NaN   0.00  0.00     NaN   2.70   2.30  AS,MVP-16,GG
14      0.0      NaN   0.00  0.00     NaN   1.80   2.10  AS,MVP-16,GG
15     -1.0      NaN   4.37  4.13   0.973   4.71   4.66            GG
16     -7.0      NaN   4.31  4.11   0.973   4.49   4.45            GG
17     -2.0      NaN   4.67  4.47   0.975   4.56   4.51            AS
18     32.0     22.0   5.17  4.95   0.971   4.54   4.49           NaN
19     -1.0      2.0   4.31  4.05   0.972   4.56   4.53           NaN
20      6.0      1.0   4.60  4.40   0.976   4.51   4.45            GG
21      2.0      7.0   4.18  3.91   0.972   4.41   4.38            GG
22     20.0     16.0   4.74  4.49   0.975   4.44   4.42           NaN
23      5.0     16.0   3.93  3.42   0.976   4.43   4.40           NaN
24     37.0     12.0   4.94  4.00   0.972   4.36   4.31           NaN
25     50.0     61.0   2.41  1.35   0.957   2.68   2.65           NaN
26     23.0      0.0   5.14  4.50   0.986   4.76   4.70           NaN
27     -8.0    -14.0   2.18  1.70   0.956   2.64   2.61           NaN
28    -12.0      0.0   3.75  3.32   0.984   4.80   4.75           NaN
29     -2.0     24.0   4.13  3.11   0.973   4.40   4.36           NaN
30      NaN      NaN    NaN   NaN     NaN    NaN    NaN           NaN
31     -1.0      7.0   2.18  1.52   0.954   2.62   2.60           NaN
32    -43.0     -9.0   4.14  3.75   0.984   4.76   4.73           NaN
33     -2.0    -13.0   3.25  2.89   0.972   4.36   4.33           NaN
34      NaN      NaN    NaN   NaN     NaN    NaN    NaN           NaN
35    160.0      0.0   6.00  2.00   0.995   9.30   9.20           NaN
36     -8.0     15.0   4.61  3.50   0.983   4.63   4.60           NaN
37     31.0     11.0   3.30  2.28   0.952   2.60   2.59           NaN
38      5.0     18.0   3.70  3.00   0.977   4.43   4.40           NaN
39     48.0      0.0  10.80  3.00   0.993   9.36   9.20           NaN
40      NaN      NaN    NaN   NaN     NaN    NaN    NaN           NaN
41      0.0      0.0   0.00  0.00     NaN   2.70   1.90           NaN
42      0.0      NaN    NaN   NaN     NaN    NaN    NaN           NaN

[43 rows x 25 columns]

In [3]:
df_vizquel_defensa

,Year,Age,Tm,Pos,Lg,G,GS,CG,Inn,Ch,...,Rtot,Rdrs,Rtot/yr,Rdrs/yr,RF/9,RF/G,lgFld%,lgRF9,lgRFG,Awards
0,1989,22,SEA,SS,AL,143,131,95.0,1124.0,614.0,...,6.0,NaN,7.0,NaN,4.77,4.17,0.971,4.79,4.74,NaN
1,1990,23,SEA,SS,AL,81,78,67.0,680.0,349.0,...,13.0,NaN,22.0,NaN,4.53,4.22,0.973,4.74,4.69,NaN
2,1991,24,SEA,SS,AL,138,123,114.0,1134.1,659.0,...,14.0,NaN,14.0,NaN,5.13,4.68,0.971,4.67,4.66,NaN
3,1991,24,SEA,2B,AL,1,0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,0.00,0.00,NaN,5.40,5.20,NaN
4,1992,25,SEA,SS,AL,136,128,120.0,1152.0,633.0,...,13.0,NaN,13.0,NaN,4.89,4.60,0.969,4.71,4.69,NaN
5,1993,26,SEA,SS,AL,155,150,140.0,1330.2,735.0,...,16.0,NaN,14.0,NaN,4.87,4.65,0.973,4.69,4.64,GG
6,1993,26,SEA,DH,AL,2,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GG
7,1994,27,CLE,SS,AL,69,68,66.0,612.2,323.0,...,4.0,NaN,8.0,NaN,4.66,4.59,0.969,4.64,4.60,GG
8,1995,28,CLE,SS,AL,136,135,125.0,1187.0,624.0,...,1.0,NaN,1.0,NaN,4.66,4.52,0.974,4.71,4.65,GG
9,1996,29,CLE,SS,AL,150,149,135.0,1312.1,693.0,...,1.0,NaN,1.0,NaN,4.62,4.49,0.971,4.66,4.64,GG
10,1997,30,CLE,SS,AL,152,149,141.0,1307.1,684.0,...,2.0,NaN,1.0,NaN,4.64,4.43,0.974,4.55,4.51,GG
11,1998,31,CLE,SS,AL,151,149,134.0,1316.0,720.0,...,9.0,NaN,8.0,NaN,4.89,4.74,0.972,4.71,4.66,"AS,GG"
12,1999,32,CLE,SS,AL,143,140,121.0,1214.1,632.0,...,14.0,NaN,14.0,NaN,4.57,4.31,0.970,4.73,4.66,"AS,MVP-16,GG"
13,1999,32,CLE,OF,AL,1,0,0.0,1.0,0.0,...,0.0,NaN,0.0,NaN,0.00,0.00,NaN,2.70,2.30,"AS,MVP-16,GG"
14,1999,32,CLE,RF,AL,1,0,0.0,1.0,0.0,...,0.0,NaN,0.0,NaN,0.00,0.00,NaN,1.80,2.10,"AS,MVP-16,GG"
15,2000,33,CLE,SS,AL,156,154,140.0,1328.2,648.0,...,-1.0,NaN,-1.0,NaN,4.37,4.13,0.973,4.71,4.66,GG
16,2001,34,CLE,SS,AL,154,152,140.0,1320.2,640.0,...,-8.0,NaN,-7.0,NaN,4.31,4.11,0.973,4.49,4.45,GG
17,2002,35,CLE,SS,AL,150,148,141.0,1291.0,677.0,...,-2.0,NaN,-2.0,NaN,4.67,4.47,0.975,4.56,4.51,AS
18,2003,36,CLE,SS,AL,64,63,59.0,551.1,324.0,...,15.0,10.0,32.0,22.0,5.17,4.95,0.971,4.54,4.49,NaN
19,2004,37,CLE,SS,AL,147,141,126.0,1245.0,607.0,...,-1.0,2.0,-1.0,2.0,4.31,4.05,0.972,4.56,4.53,NaN
20,2005,38,SFG,SS,NL,150,144,141.0,1292.1,668.0,...,7.0,1.0,6.0,1.0,4.60,4.40,0.976,4.51,4.45,GG
21,2006,39,SFG,SS,NL,152,148,131.0,1281.1,599.0,...,2.0,7.0,2.0,7.0,4.18,3.91,0.972,4.41,4.38,GG
22,2007,40,SFG,SS,NL,143,136,130.0,1219.1,651.0,...,20.0,16.0,20.0,16.0,4.74,4.49,0.975,4.44,4.42,NaN
23,2008,41,SFG,SS,NL,84,76,61.0,657.2,289.0,...,3.0,9.0,5.0,16.0,3.93,3.42,0.976,4.43,4.40,NaN
24,2009,42,TEX,SS,AL,27,22,17.0,196.2,108.0,...,6.0,2.0,37.0,12.0,4.94,4.00,0.972,4.36,4.31,NaN
25,2009,42,TEX,3B,AL,20,9,8.0,101.0,27.0,...,4.0,5.0,50.0,61.0,2.41,1.35,0.957,2.68,2.65,NaN
26,2009,42,TEX,2B,AL,16,14,13.0,126.0,72.0,...,2.0,0.0,23.0,0.0,5.14,4.50,0.986,4.76,4.70,NaN
27,2010,43,CHW,3B,AL,83,62,55.0,582.1,144.0,...,-4.0,-7.0,-8.0,-14.0,2.18,1.70,0.956,2.64,2.61,NaN
28,2010,43,CHW,2B,AL,19,18,12.0,151.0,63.0,...,-2.0,0.0,-12.0,0.0,3.75,3.32,0.984,4.80,4.75,NaN
29,2010,43,CHW,SS,AL,9,8,4.0,61.0,28.0,...,0.0,1.0,-2.0,24.0,4.13,3.11,0.973,4.40,4.36,NaN
30,2010,43,CHW,DH,AL,1,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,2011,44,CHW,3B,AL,29,20,17.0,182.0,44.0,...,0.0,1.0,-1.0,7.0,2.18,1.52,0.954,2.62,2.60,NaN
32,2011,44,CHW,2B,AL,16,14,10.0,130.1,61.0,...,-5.0,-1.0,-43.0,-9.0,4.14,3.75,0.984,4.76,4.73,NaN
33,2011,44,CHW,SS,AL,9,8,7.0,72.0,26.0,...,0.0,-1.0,-2.0,-13.0,3.25,2.89,0.972,4.36,4.33,NaN
34,2011,44,CHW,DH,AL,3,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2011,44,CHW,1B,AL,1,0,0.0,3.0,2.0,...,0.0,0.0,160.0,0.0,6.00,2.00,0.995,9.30,9.20,NaN
36,2012,45,TOR,2B,AL,24,18,16.0,164.0,84.0,...,-1.0,2.0,-8.0,15.0,4.61,3.50,0.983,4.63,4.60,NaN
37,2012,45,TOR,3B,AL,18,10,9.0,111.2,44.0,...,3.0,1.0,31.0,11.0,3.30,2.28,0.952,2.60,2.59,NaN
38,2012,45,TOR,SS,AL,10,9,6.0,73.0,30.0,...,0.0,1.0,5.0,18.0,3.70,3.00,0.977,4.43,4.40,NaN
39,2012,45,TOR,1B,AL,2,0,0.0,5.0,6.0,...,0.0,0.0,48.0,0.0,10.80,3.00,0.993,9.36,9.20,NaN
40,2012,45,TOR,DH,AL,1,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2012,45,TOR,LF,AL,1,0,0.0,0.2,0.0,...,0.0,0.0,0.0,0.0,0.00,0.00,NaN,2.70,1.90,NaN
42,2012,45,TOR,OF,AL,1,0,0.0,0.2,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#Aquí supe cuantas y cuales columnas había y saber cuales iba a quitar

df_vizquel_defensa.columns

Index(['Year', 'Age', 'Tm', 'Pos', 'Lg', 'G', 'GS', 'CG', 'Inn', 'Ch', 'PO',
       'A', 'E', 'DP', 'Fld%', 'Rtot', 'Rdrs', 'Rtot/yr', 'Rdrs/yr', 'RF/9',
       'RF/G', 'lgFld%', 'lgRF9', 'lgRFG', 'Awards'],
      dtype='object')

In [10]:
#Usé .loc para escoger

df_vizquel_defensa_filtrado = df_vizquel_defensa.loc[:, ['Fld%', 'A', 'DP', 'E']]

df_vizquel_defensa_filtrado

        Fld%      A     DP     E
0      0.971  388.0  102.0  18.0
1      0.980  239.0   48.0   7.0
2      0.980  422.0  105.0  13.0
3        NaN    0.0    0.0   0.0
4      0.989  403.0   92.0   7.0
5      0.980  475.0  108.0  15.0
6        NaN    NaN    NaN   NaN
7      0.981  204.0   54.0   6.0
8      0.986  405.0   84.0   9.0
9      0.971  447.0   91.0  20.0
10     0.985  429.0   98.0  10.0
11     0.993  442.0   94.0   5.0
12     0.976  396.0   88.0  15.0
13       NaN    0.0    0.0   0.0
14       NaN    0.0    0.0   0.0
15     0.995  414.0   99.0   3.0
16     0.989  414.0   88.0   7.0
17     0.990  431.0   98.0   7.0
18     0.978  203.0   59.0   7.0
19     0.982  396.0   91.0  11.0
20     0.988  426.0   81.0   8.0
21     0.993  390.0   87.0   4.0
22     0.986  444.0   90.0   9.0
23     0.993  179.0   43.0   2.0
24  1000.000   76.0   22.0   0.0
25  1000.000   22.0    2.0   0.0
26  1000.000   49.0   12.0   0.0
27     0.979  110.0   15.0   3.0
28  1000.000   41.0    9.0   0.0
29  1000.000   15.0    6.0   0.0
30       NaN    NaN    NaN   NaN
31  1000.000   31.0    2.0   0.0
32     0.984   37.0    7.0   1.0
33  1000.000   18.0    3.0   0.0
34       NaN    NaN    NaN   NaN
35  1000.000    1.0    0.0   0.0
36  1000.000   52.0   13.0   0.0
37     0.932   31.0    3.0   3.0
38  1000.000   20.0    3.0   0.0
39  1000.000    0.0    0.0   0.0
40       NaN    NaN    NaN   NaN
41       NaN    0.0    0.0   0.0
42       NaN    0.0    0.0   0.0